defaults:
  resources:
    instance-type: C4

jobs:
  CloneRepo:
    resources:
      instance-type: C4
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/GhaidaAlAtoum/test_gradient_workflow.git