defaults:
  resources:
    instance-type: P5000
on:
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: context.event.github.url
  HelloWorld:
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    env:
      # ghaida: secret:KAGGLE_USERNAME
      # bash: secret:KAGGLE_USERNAME
      abood: temp
      # KAGGLE_KEY: secret:KAGGLE_KEY
    uses: script@v1
    with:
      script: |-
        cd /inputs/repo
        python listenv.py
        env
      image: tensorflow/tensorflow:2.12.0-gpu
# gja8672/test-gradient:sha-d8a940b
