defaults:
  resources:
    instance-type: P5000
  # env:
  #   KAGGLE_KEY: secret:kagglekey
  #   KAGGLE_USERNAME: secret:kaggleusername

on:
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/GhaidaAlAtoum/test_gradient_workflow.git
  GetFairFaceDataset:
    outputs:
      fair-face-volume:
        type: volume
    uses: script@v1
    with:
      script: |-
        echo "-------------------------------------- 1"
        pip install --upgrade pip setuptools wheel
        pip install kaggle
        echo "-------------------------------------- 2"
        kaggle datasets download -d ghaidaalatoum/fairface -p /outputs/fair-face-volume/ --unzip 
        echo "-------------------------------------- 3"
        ls  /outputs/fair-face-volume/
        echo "-------------------------------------- 4"
      image: tensorflow/tensorflow:2.12.0-gpu

  Train:
    needs:
      - CloneRepo
      - GetFairFaceDataset
    inputs:
      repo: CloneRepo.outputs.repo
      fair-face-volume: GetFairFaceDataset.outputs.fair-face-volume
    outputs:
      training-output-dataset:
        type: dataset
        with:
          ref: ds15a8t3834q515
    uses: script@v1
    with:
      script: |-
        echo "-------------------------------------- 0 - List Training Data"
        ls /inputs/fair-face-volume/fairface/
        echo "-------------------------------------- 2 - Access Repo" 
        cd /inputs/repo
        ls
        echo "-------------------------------------- 1 - Setup ENV"
        source setup.sh
        echo "-------------------------------------- 3 - Run Training"
        python train.py
        echo "-------------------------------------- 4 - List outputs"
        ls /outputs
      image: tensorflow/tensorflow:2.12.0-gpu

# https://docs.digitalocean.com/products/paperspace/workflows/concepts/environment-variables/