defaults:
  resources:
    instance-type: P5000
  env:
    KAGGLE_KEY:  ${{ secrets.KAGGLE_KEY }}
    KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}

on:
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/GhaidaAlAtoum/test_gradient_workflow.git
  HelloWorld:
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    uses: script@v1
    with:
      script: |-
        cd /inputs/repo
        python listenv.py
        env
      image: tensorflow/tensorflow:2.12.0-gpu

# https://docs.digitalocean.com/products/paperspace/workflows/concepts/environment-variables/