'on':
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    resources:
      instance-type: P5000
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: context.event.github.url
  HelloWorld:
    env:
      KAGGLE_USERNAME: secret:KAGGLE_USERNAME
      KAGGLE_KEY: secret:KAGGLE_KEY
    resources:
      instance-type: P5000
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    uses: script@v1
    with:
      script: |-
        cd /inputs/repo
        echo "-------------------------------------- 0"
        printenv
        echo "-------------------------------------- 1"
        source setup.sh
        echo "-------------------------------------- 2"
        python hello.py
      image: tensorflow/tensorflow:2.12.0-gpu
# gja8672/test-gradient:sha-d8a940b
