defaults:
  resources:
    instance-type: P5000
  # env:
  #   KAGGLE_KEY: secret:kagglekey
  #   KAGGLE_USERNAME: secret:kaggleusername

on:
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/GhaidaAlAtoum/test_gradient_workflow.git
  HelloWorld:
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    outputs:
      my-dataset:
        type: dataset
        with:
          ref: dsiyub4jejwfw7b
    uses: script@v1
    with:
      script: |-
        cd /inputs/repo
        echo "-------------------------------------- 1"
        source setup.sh
        echo "-------------------------------------- 2"
        kaggle datasets download -d ghaidaalatoum/fairface -p /outputs/my-dataset/ --unzip 
        echo "-------------------------------------- 3"
      image: tensorflow/tensorflow:2.12.0-gpu
# gja8672/test-gradient:sha-d8a940b

# https://docs.digitalocean.com/products/paperspace/workflows/concepts/environment-variables/