'on':
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    resources:
      instance-type: C5
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: context.event.github.url
  HelloWorld:
    resources:
      instance-type: C5
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    uses: script@v1
    with:
      script: |-
        python3 -m pip install --upgrade pip setuptools wheel
        pip install matplotlib
        pip install numpy
        pip install scikit-learn
        cd /inputs/repo
        python hello.py
      image: tensorflow/tensorflow:2.12.0rc1-gpu
