on:
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    resources:
      instance-type: P5000
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: context.event.github.url
  HelloWorld:
    resources:
      instance-type: P5000
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    uses: script@v1
    env:
      # KAGGLE_USERNAME: secret:<KAGGLE_USERNAME>
      # KAGGLE_KEY: secret:KAGGLE_KEY
      # TEMP: secret:temp
      HEHE: hehe
    with:
      script: |-
        cd /inputs/repo
        echo "======"
        echo $HEHE
        echo "======"
      image: tensorflow/tensorflow:2.12.0-gpu
# gja8672/test-gradient:sha-d8a940b
