defaults:
  resources:
    instance-type: P5000
  # env:
  #   KAGGLE_KEY: secret:kagglekey
  #   KAGGLE_USERNAME: secret:kaggleusername

on:
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/GhaidaAlAtoum/test_gradient_workflow.git
  GetFairFaceDataset:
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    outputs:
      fair-face-volume:
        type: volume
    uses: script@v1
    with:
      script: |-
        cd /inputs/repo
        echo "-------------------------------------- 1"
        pip install --upgrade pip setuptools wheel
        pip install kaggle
        echo "-------------------------------------- 2"
        kaggle datasets download -d ghaidaalatoum/fairface -p /outputs/fair-face-volume/ --unzip 
        echo "-------------------------------------- 3"
        ls  /outputs/fair-face-volume/
        echo "-------------------------------------- 4"
      image: tensorflow/tensorflow:2.12.0-gpu
  Train:
    needs:
      - CloneRepo
      - GetFairFaceDataset
    inputs:
      fair-face-volume: GetFairFaceDataset.outputs.fair-face-volume
    uses: script@v1
    with:
      script: |-
        echo "-------------------------------------- 0"
        ls /inputs
        echo "-------------------------------------- 1"
        ls /outputs
    image: tensorflow/tensorflow:2.12.0-gpu

# https://docs.digitalocean.com/products/paperspace/workflows/concepts/environment-variables/